region                            = "ap-southeast-1"
ami_id                            = "ami-00d8fc944fb171e29"
instance_type                     = "t2.micro"
instance_name                     = "terra-instance-1"
vpc_cidr                          = "10.0.0.0/16"
vpc_name                          = "terra-vpc-1"
public_subnet_1_cidr              = "10.0.1.0/24"
public_subnet_2_cidr              = "10.0.2.0/24"
private_subnet_1_cidr             = "10.0.3.0/24"
private_subnet_2_cidr             = "10.0.4.0/24"
public_subnet_1_availability_zone = "ap-southeast-1a"
public_subnet_2_availability_zone = "ap-southeast-1b"
private_subnet_1_availability_zone = "ap-southeast-1a"
private_subnet_2_availability_zone = "ap-southeast-1b"
public_subnet_1_name              = "public-terra-subnet-1"
public_subnet_2_name              = "public-terra-subnet-2"


